apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.name }}
  description: Stack for ${{values.name }}
  annotations:
    pulumi.com/project-slug: ${{values.stack}}
spec:
  owner: infrastructure
  domain: gitops-platform
  type: service
  lifecycle: experimental
  system: gitops-system
