apiVersion: pulumi.com/v1
kind: Program
metadata:
  name: ${{values.name }}
program:
  resources:
    bucket:
      type: aws:s3:BucketV2
    bucketOwnershipControls:
      type: aws:s3:BucketOwnershipControls
      properties:
        bucket: ${bucket.id}
        rule:
          objectOwnership: BucketOwnerPreferred
    bucketPublicAccessBlock:
      type: aws:s3:BucketPublicAccessBlock
      properties:
        bucket: ${bucket.id}
        blockPublicAcls: false
        blockPublicPolicy: false
        ignorePublicAcls: false
        restrictPublicBuckets: false
    bucketACL:
      type: aws:s3:BucketAclV2
      properties:
        bucket: ${bucket.id}
        acl: public-read
      options:
        dependsOn:
        - ${bucketOwnershipControls}
        - ${bucketPublicAccessBlock}
    webSiteContent:
      type: aws:s3:BucketWebsiteConfigurationV2
      properties:
        bucket: ${bucket.id}
        indexDocument:
          suffix: index.html
    index.html:
      type: aws:s3:BucketObject
      options:
        dependsOn:
        - ${webSiteContent}
        - ${bucketACL}
      properties:
        bucket: ${bucket.id}
        content: |
          ${{values.content}}
        contentType: text/html
        acl: public-read
  outputs:
    url: http://${webSiteContent.websiteEndpoint}
---
apiVersion: pulumi.com/v1
kind: Stack
metadata:
  name: ${{values.name }}
spec:
  stack: ${{values.stack}}
  envRefs:
    AWS_ACCESS_KEY_ID:
      type: Secret
      secret:
        name: ${{values.ecs}}
        key: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      type: Secret
      secret:
        name: ${{values.ecs}}
        key: AWS_SECRET_ACCESS_KEY
    {%- if values.ecs == 'secret' %}
    AWS_SESSION_TOKEN:
      type: Secret
      secret:
        name: ${{values.ecs}}
        key: AWS_SESSION_TOKEN
    {%- endif %}
  programRef:
    name: ${{values.name }}
  destroyOnFinalize: false
  config:
    aws:region: ${{values.region}}
