apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: pull-request
  title: Create S3 Bucket
  description: |
    A template for creating a new S3 Bucket.
spec:
  owner: backstage/techdocs-core
  type: service

  parameters:
  - title: Fill in some steps
    required:
    - name
    properties:
      name:
        title: Name
        type: string
        description: Unique name of the component
        ui:field: EntityNamePicker
        ui:autofocus: true
      content:
        title: Website Content
        type: string
        description: |
          The content of the website
          This will be written to the index.html file
      region:
        title: Region
        type: string
        description: |
          The region to deploy the bucket
      stack:
        title: Stack
        type: string
        description: |
          The stack to deploy the bucket
          This will be used to group the resources
          and to name the pulumi stack    

  - title: Choose a location
    required:
    - repoUrl
    properties:
      repoUrl:
        title: Repository Location
        type: string
        ui:field: RepoUrlPicker
        ui:options:
          allowedHosts:
          - github.com

  steps:
  - id: fetch-base
    name: Fetch Base
    action: fetch:template
    input:
      url: ./template
      values:
        name: ${{parameters.name}}
        content: ${{parameters.content}}
        region: ${{parameters.region}}
        stack: ${{parameters.stack}}

  - id: publish
    name: Publish
    action: publish:github:pull-request
    input:
      repoUrl: github.com/my-backstage-demo/pulumi-infrastructure
      title: "Create new project: ${{parameters.name}}"
      branchName: create-${{parameters.name}}
      description: |
        # New S3 Bucket with name ${{parameters.name}}
        
        delivered by FLux to the Pulumi operator
      targetPath: .

  output:
    links:
    - url: ${{steps.publish.output.remoteUrl}}
      title: "Go to PR"
