apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: pull-request
  title: Create static website
  description: |
    A template for creating a new static website on an AWS S3 bucket.
spec:
  owner: backstage/techdocs-core
  type: service

  parameters:
  - title: Fill in some steps
    required:
    - name
    properties:
      name:
        title: Name
        type: string
        maxLength: 16
        pattern: "^[a-z0-9-]*$"
        description: Unique name of the component
        ui:field: EntityNamePicker
        ui:autofocus: true
      content:
        title: Website Content
        type: string
        ui:widget: textarea
        ui:options:
          rows: 10
        description: |
          The content of the website
          This will be written to the index.html file
          You can use html tags here
      region:
        title: Region
        type: string
        enum:
        - eu-central-1
        - us-east-1
        - us-east-2
        - us-west-1
        - us-west-2
        default: eu-central-1
        description: |
          The region to deploy the bucket to
      stack:
        title: Select stack
        type: string
        enum:
        - dev
        - staging
        - prod
        enumNames:
        - Development
        - Staging
        - Production
        description: The pulumi stack to use

  steps:
  - id: fetch-base
    name: Fetch Base
    action: fetch:template
    input:
      url: ./template
      values:
        name: ${{parameters.name}}
        content: ${{parameters.content}}
        region: ${{parameters.region}}
        stack: ediri/${{parameters.name}}/${{parameters.stack}}

  - id: publish
    name: Publish
    action: publish:github:pull-request
    input:
      repoUrl: github.com?repo=pulumi-infrastructure&owner=my-backstage-demo
      title: "Create new project: ${{parameters.name}}"
      branchName: create-${{parameters.name}}
      description: |
        # New S3 Bucket with name ${{parameters.name}}
        
        delivered by FLux to the Pulumi operator
      targetPath: .

  output:
    links:
    - url: ${{steps.publish.output.remoteUrl}}
      title: "Go to PR"
